version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      client:
        condition: service_started


  client:
    build: ./frontend
    ports:
      - "350:350"
    depends_on:
      api:
        condition: service_started

  api:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      migrations:
        condition: service_completed_successfully

  migrations:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    healthcheck:
      test: pg_isready -U admin -d alma_market
      interval: 3s
      retries: 10
      timeout: 3s
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  pgdata:
