# Generated by Django 4.2 on 2023-07-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_address_name_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
    ]
