# Generated by Django 4.1.7 on 2023-05-01 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.PositiveIntegerField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ItemCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.characteristic')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.item')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
                'unique_together': {('item', 'characteristic')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='characteristic',
            field=models.ManyToManyField(through='goods.ItemCharacteristic', to='goods.characteristic'),
        ),
    ]
