# Generated by Django 4.2 on 2023-07-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_category_name_alter_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='images/default_image.png', upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/default_image.png', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
