# Generated by Django 4.2 on 2023-07-27 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: "+79991234567".', regex='^\\+7\\d{10}$')]),
        ),
    ]
